name: Scrape Events

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scraper/requirements.txt ]; then
            pip install -r scraper/requirements.txt
          else
            # Install common dependencies used by scrapers
            pip install requests beautifulsoup4 pandas lxml tqdm python-dateutil ics
          fi
          
      - name: Debug directory structure
        run: |
          echo "Current working directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Full directory tree:"
          find . -type d | sort
          
      - name: Run scrapers
        run: |
          # Add the scraper directory to PYTHONPATH
          export PYTHONPATH=$PYTHONPATH:$(pwd)/scraper
          echo "PYTHONPATH is now: $PYTHONPATH"
          cd scraper/tech
          python run_all.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/data/events.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update events data [skip ci]" && git push)
          
      # If you're using Vercel for deployment
      - name: Deploy to Vercel
        if: success()
        run: |
          npx vercel --token ${VERCEL_TOKEN} --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }} 