name: Update NYC Events

on:
  schedule:
    # Run twice a week (Monday and Thursday at 2:00 UTC)
    - cron: '0 2 * * 1,4'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run event scrapers
        run: |
          # Debug directory structure
          echo "Current working directory: $(pwd)"
          echo "Checking if scraper/tech exists:"
          if [ -d "scraper/tech" ]; then
            echo "scraper/tech directory exists"
          else
            echo "scraper/tech directory does NOT exist"
            echo "Available directories in scraper:"
            ls -la scraper/
          fi
          
          # Set PYTHONPATH and run the scraper
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          echo "Running scraper with PYTHONPATH: $PYTHONPATH"
          python -m scraper.tech.run_all --output public/data/events.json
        
      - name: Check for changes
        id: git-check
        run: |
          git add public/data/events.json
          git status --porcelain
          echo "modified=$(if git status --porcelain | grep 'public/data/events.json'; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT

      - name: Commit and push if changed
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update events data [skip ci]" public/data/events.json
          git push 